name: Monthly Crawl

on:
  schedule:
    - cron: '0 8 1 * *'  # Runs on the 1st of each month at 08:00 UTC
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python main.py
        env:
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
          LETTERBOXD_USER: ${{ secrets.LETTERBOXD_USER }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
